apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaled-object-name1
spec:
  scaleTargetRef:
    name: nginx-keda
  pollingInterval: 5
  maxReplicaCount: 10
  minReplicaCount: 1
  triggers:
  - type: azure-blob
    metadata:
      connectionFromEnv: blob_connection_string
      accountName: abcd1234276azure   
      blobContainerName: keda
      blobCount: '2'

      
      